set_input_delay -clock [get_clocks dco_p] -clock_fall -min -add_delay -0.500 [get_ports {a_d0_n[0]}]
set_input_delay -clock [get_clocks dco_p] -clock_fall -max -add_delay 0.000 [get_ports {a_d0_n[0]}]
set_input_delay -clock [get_clocks dco_p] -min -add_delay -0.500 [get_ports {a_d0_n[0]}]
set_input_delay -clock [get_clocks dco_p] -max -add_delay 0.000 [get_ports {a_d0_n[0]}]
set_input_delay -clock [get_clocks dco_p] -clock_fall -min -add_delay -0.500 [get_ports {a_d0_p[0]}]
set_input_delay -clock [get_clocks dco_p] -clock_fall -max -add_delay 0.000 [get_ports {a_d0_p[0]}]
set_input_delay -clock [get_clocks dco_p] -min -add_delay -0.500 [get_ports {a_d0_p[0]}]
set_input_delay -clock [get_clocks dco_p] -max -add_delay 0.000 [get_ports {a_d0_p[0]}]
set_input_delay -clock [get_clocks dco_p] -clock_fall -min -add_delay -0.500 [get_ports {a_d1_n[0]}]
set_input_delay -clock [get_clocks dco_p] -clock_fall -max -add_delay 0.000 [get_ports {a_d1_n[0]}]
set_input_delay -clock [get_clocks dco_p] -min -add_delay -0.500 [get_ports {a_d1_n[0]}]
set_input_delay -clock [get_clocks dco_p] -max -add_delay 0.000 [get_ports {a_d1_n[0]}]
set_input_delay -clock [get_clocks dco_p] -clock_fall -min -add_delay -0.500 [get_ports {a_d1_p[0]}]
set_input_delay -clock [get_clocks dco_p] -clock_fall -max -add_delay 0.000 [get_ports {a_d1_p[0]}]
set_input_delay -clock [get_clocks dco_p] -min -add_delay -0.500 [get_ports {a_d1_p[0]}]
set_input_delay -clock [get_clocks dco_p] -max -add_delay 0.000 [get_ports {a_d1_p[0]}]
set_input_delay -clock [get_clocks fco_p] -min -add_delay 4.000 [get_ports user_pushbutton_g]
set_input_delay -clock [get_clocks fco_p] -max -add_delay 4.000 [get_ports user_pushbutton_g]
set_clock_groups -asynchronous -group [get_clocks fco_p] -group [get_clocks clk_out1_clk_wiz_1]
set_clock_groups -asynchronous -group [get_clocks clk_out1_clk_wiz_1] -group [get_clocks clk_out1_clk_wiz_2]
set_clock_groups -asynchronous -group [get_clocks clk_out2_clk_wiz_0] -group [get_clocks clk_out1_clk_wiz_2]
