set_property IOSTANDARD LVDS [get_ports dco_p]
set_property IOSTANDARD LVDS [get_ports dco_n]
set_property PACKAGE_PIN K39 [get_ports dco_p]
set_property PACKAGE_PIN K40 [get_ports dco_n]
create_clock -period 2.000 -name dco_p -waveform {0.000 1.000} [get_ports dco_p]

set_property IOSTANDARD LVDS [get_ports fco_p]
set_property IOSTANDARD LVDS [get_ports fco_n]
set_property PACKAGE_PIN L39 [get_ports fco_p]

set_property IOSTANDARD LVDS [get_ports osc_in_p]
set_property IOSTANDARD LVDS [get_ports osc_in_n]
#set_property PACKAGE_PIN H19 [get_ports osc_in_p]
#set_property PACKAGE_PIN G18 [get_ports osc_in_n] ##vc709 osc_in
set_property PACKAGE_PIN L39 [get_ports osc_in_p]
set_property PACKAGE_PIN L40 [get_ports osc_in_n]  ##dac3484evm cdce62005 in
create_clock -period 5.000 -name osc_in_p -waveform {0.000 2.500} [get_ports osc_in_p]

set_property IOSTANDARD LVDS [get_ports {a_d0_p[0]}]
set_property IOSTANDARD LVDS [get_ports {a_d0_n[0]}]
set_property IOSTANDARD LVDS [get_ports {a_d1_p[0]}]
set_property IOSTANDARD LVDS [get_ports {a_d1_n[0]}]
#set_property IOSTANDARD LVDS [get_ports a_d2_p]
#set_property IOSTANDARD LVDS [get_ports a_d2_n]
#set_property IOSTANDARD LVDS [get_ports a_d3_p]
#set_property IOSTANDARD LVDS [get_ports a_d3_n]
set_property PACKAGE_PIN K37 [get_ports {a_d0_p[0]}]
set_property PACKAGE_PIN K38 [get_ports {a_d0_n[0]}]
set_property PACKAGE_PIN N39 [get_ports a_d1_p]
set_property PACKAGE_PIN N40 [get_ports a_d1_n]
#set_property PACKAGE_PIN R40 [get_ports a_d2_p]
#set_property PACKAGE_PIN P40 [get_ports a_d2_p]
#set_property PACKAGE_PIN M39 [get_ports a_d3_p]
#set_property PACKAGE_PIN N38 [get_ports a_d3_p]

set_property IOSTANDARD LVCMOS18 [get_ports Sys_Rst_pin]

set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[15]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[0]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[4]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[6]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[8]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[9]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[14]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[13]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[10]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[7]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[5]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[2]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[1]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[11]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[12]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/data_a[3]}]
connect_debug_port u_ila_0/probe0 [get_nets [list {AD9653_top_inst/data_a[0]} {AD9653_top_inst/data_a[1]} {AD9653_top_inst/data_a[2]} {AD9653_top_inst/data_a[3]} {AD9653_top_inst/data_a[4]} {AD9653_top_inst/data_a[5]} {AD9653_top_inst/data_a[6]} {AD9653_top_inst/data_a[7]} {AD9653_top_inst/data_a[8]} {AD9653_top_inst/data_a[9]} {AD9653_top_inst/data_a[10]} {AD9653_top_inst/data_a[11]} {AD9653_top_inst/data_a[12]} {AD9653_top_inst/data_a[13]} {AD9653_top_inst/data_a[14]} {AD9653_top_inst/data_a[15]}]]
connect_debug_port dbg_hub/clk [get_nets fco]


set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[1]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[3]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[8]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[2]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[15]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[12]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[7]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[11]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[13]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[9]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[5]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[10]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[4]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[0]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[6]}]
set_property MARK_DEBUG true [get_nets {AD9653_top_inst/din[14]}]
set_property IOSTANDARD LVDS [get_ports a_d0_p]
set_property IOSTANDARD LVDS [get_ports a_d1_p]
set_property IOSTANDARD LVCMOS18 [get_ports user_pushbutton_g]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list crg_dcms_inst/dcm_fco/U0/clk_out1]]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {AD9653_top_inst/din[0]} {AD9653_top_inst/din[1]} {AD9653_top_inst/din[2]} {AD9653_top_inst/din[3]} {AD9653_top_inst/din[4]} {AD9653_top_inst/din[5]} {AD9653_top_inst/din[6]} {AD9653_top_inst/din[7]} {AD9653_top_inst/din[8]} {AD9653_top_inst/din[9]} {AD9653_top_inst/din[10]} {AD9653_top_inst/din[11]} {AD9653_top_inst/din[12]} {AD9653_top_inst/din[13]} {AD9653_top_inst/din[14]} {AD9653_top_inst/din[15]}]]


### dac spi interface
set_property IOSTANDARD LVCMOS18 [get_ports SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports SDENB]
set_property IOSTANDARD LVCMOS18 [get_ports SDO]


set_property PACKAGE_PIN J30 [get_ports SDENB]
set_property PACKAGE_PIN P31 [get_ports SDO]
###


set_property OFFCHIP_TERM NONE [get_ports SCLK]
set_property OFFCHIP_TERM NONE [get_ports SDENB]
set_property OFFCHIP_TERM NONE [get_ports SDIO]
set_property PACKAGE_PIN R30 [get_ports {Q_p[0]}]
set_property PACKAGE_PIN N28 [get_ports {Q_p[1]}]
set_property PACKAGE_PIN W30 [get_ports {Q_p[2]}]
set_property PACKAGE_PIN M36 [get_ports {Q_p[3]}]
set_property PACKAGE_PIN F40 [get_ports {Q_p[4]}]
set_property PACKAGE_PIN G41 [get_ports {Q_p[5]}]
set_property PACKAGE_PIN H40 [get_ports {Q_p[6]}]
set_property PACKAGE_PIN P41 [get_ports {Q_p[7]}]
set_property PACKAGE_PIN U31 [get_ports {Q_p[8]}]
set_property PACKAGE_PIN M28 [get_ports {Q_p[9]}]
set_property PACKAGE_PIN T29 [get_ports {Q_p[10]}]
set_property PACKAGE_PIN R28 [get_ports {Q_p[12]}]
set_property PACKAGE_PIN Y29 [get_ports {Q_p[13]}]
set_property PACKAGE_PIN K37 [get_ports {Q_p[14]}]
set_property PACKAGE_PIN R40 [get_ports {Q_p[15]}]
set_property PACKAGE_PIN K29 [get_ports {Q_p[11]}]
set_property PACKAGE_PIN V29 [get_ports frame_p]
set_property PACKAGE_PIN M32 [get_ports DataCLk_p]
set_property PACKAGE_PIN V30 [get_ports SYNC_p]
set_property IOSTANDARD LVDS [get_ports frame_p]
set_property IOSTANDARD LVCMOS18 [get_ports SDIO]
set_property IOSTANDARD LVDS [get_ports SYNC_p]
set_property IOSTANDARD LVDS [get_ports DataCLk_p]
set_property PACKAGE_PIN AV40 [get_ports user_pushbutton_g]
set_property PACKAGE_PIN N38 [get_ports a_d0_p]
set_property PACKAGE_PIN N31 [get_ports SDIO]
set_property PACKAGE_PIN U28 [get_ports SCLK]
set_property IOSTANDARD LVDS [get_ports {Q_p[15]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[14]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[13]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[12]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[11]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[10]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[9]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[8]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[7]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[6]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[5]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[4]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[3]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[2]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[1]}]
set_property IOSTANDARD LVDS [get_ports {Q_p[0]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
